services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    ports:
      - "1433:1433"
    restart: always
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: "MyPass@word"
      MSSQL_PID: "Developer"
    volumes:
      - ./db-data:/var/opt/mssql