services:
  # 從 Docker Hub 下載 image 後啟動 container
  my-web-with-nginx:
    image: nginx:latest
    container_name: my-nginx-compose
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html
    restart: always
    
  # # 從 Dockerfile 建立 image 後啟動 container
  # my-web-with-custom-image:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: my-web-with-custom-image-compose
  #   ports:
  #     - "5500:80"
  #   restart: always